import { Navbar } from "@/components/landing/Navbar";
import { Footer } from "@/components/landing/Footer";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <Navbar />
      <main className="flex-1 bg-background pt-32 pb-16">
        <div className="mx-auto max-w-3xl px-6 text-foreground">
          <h1 className="text-4xl font-bold tracking-tight">Terms of Service</h1>
          <p className="mt-4 text-muted-foreground">Last updated: {new Date().toLocaleDateString()}</p>
          
          <div className="mt-10 space-y-8">
            <section>
              <h2 className="text-2xl font-semibold">1. Acceptance of Terms</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                By accessing and using Recastr, you accept and agree to be bound by the terms and provision of this agreement.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold">2. Provision of Services</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                Recastr is constantly innovating in order to provide the best possible experience for its users. You acknowledge and agree that the form and nature of the services which Recastr provides may change from time to time without prior notice to you.
              </p>
            </section>
            
            <section>
              <h2 className="text-2xl font-semibold">3. User Conduct</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                You agree to use the services only for purposes that are permitted by the Terms and any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdictions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold">4. AI-Generated Content</h2>
              <p className="mt-3 leading-relaxed text-muted-foreground">
                You are solely responsible for reviewing and verifying any content generated by Recastr before publishing. Recastr is not liable for any inaccuracies, copyright issues, or other disputes arising from the use of generated content.
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
